In [37]:
import tensorflow as tf

In [38]:
print(tf.__version__)

1.4.0


In [39]:
hello=tf.constant('Hello')

In [40]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [41]:
world=tf.constant('World')
result=hello+world
result

<tf.Tensor 'add_4:0' shape=() dtype=string>

In [42]:
type(result)

tensorflow.python.framework.ops.Tensor

In [43]:
with tf.Session() as sess:
    result=sess.run(hello+world)

In [44]:
result

b'HelloWorld'

In [45]:
tensor_1=tf.constant(1)
tensor_2=tf.constant(2)
tensor_1+tensor_2

<tf.Tensor 'add_6:0' shape=() dtype=int32>

In [46]:
sess

In [47]:
const=tf.constant(10)
fill_mat=tf.fill((4,4),10)
myzeros=tf.zeros((4,4))
myones=tf.ones((4,4))
myrandn=tf.random_normal((4,4),mean=0,stddev=0.5)
myrandu=tf.random_uniform((4,4),minval=0,maxval=0)
my_ops=[const,fill_mat,myzeros,myones,myrandn,myrandu]

In [48]:
sess=tf.InteractiveSession()

In [49]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.05077128 -0.08659003  0.32254013 -0.0863637 ]
 [ 0.07990578  0.61531067 -0.96366119 -0.85624313]
 [-0.28353727  0.43049183 -0.36941972 -0.6080389 ]
 [ 0.89242154  0.47335094 -0.31125143 -0.60174757]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]




In [50]:
a=tf.constant([ [1,2],
                [3,4] ])

In [51]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [52]:
b=tf.constant([[10],[100]])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [53]:
result=tf.matmul(a,b)
result.eval()

array([[210],
       [430]])

In [54]:
n1=tf.constant(1)
n2=tf.constant(2)

In [55]:
n3=n1+n2

In [56]:
with tf.Session() as sess:
    result=sess.run(n3)
print(result)

3


In [57]:
print(tf.get_default_graph())

In [58]:
g=tf.Graph()
print(g)

In [59]:
graph_one=tf.get_default_graph()
graph_two=tf.Graph()

In [60]:
graph_one is tf.get_default_graph()

True

In [61]:
graph_two is tf.get_default_graph()

False

In [62]:
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

True


In [63]:
graph_two is tf.get_default_graph()

False